title: Kriscieli Fonsaca
description: Psicopedagoga Clínica e Institucional
baseurl: "" # Deixe vazio para o site principal do GitHub Pages
url: "https://aakrupa.github.io/KF" # Ou o seu domínio final
markdown: kramdown
