title: Kriscieli Fonsaca
description: Psicopedagoga Clínica e Institucional
baseurl: "/KF"            # <-- O nome do seu repositório
url: "https://aakrupa.github.io"
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
